---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: content/main
  label: Home page
  create: all
  match: "**/*"
- type: directory
  path: content/about
  label: About
  create: all
  match: "**/*"
- type: directory
  path: content/team
  label: Team
  create: all
  match: "**/*"
- type: directory
  path: content/career
  label: Career
  create: all
  match: "**/*"
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
- type: directory
  path: content/sell-to-us
  label: HOW WE WORK
  create: all
  match: "**/*"
- type: directory
  path: content/application
  label: Ready to Sell
  create: all
  match: "**/*"
- type: directory
  path: content/contact-us
  label: Contact Us
  create: all
  match: "**/*"
- type: document
  path: config.toml
  label: config.toml
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.76.5
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.76.5
